# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 14, 16, 24, 8, 788651), verbose_name=b'game played'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
